local Util = require("floraverse.util")

local M = {}

---@type fun(colors: ColorScheme, opts:floraverse.Config):floraverse.Highlights
function M.get(c, opts)
  -- stylua: ignore
  return {
    Normal         = { fg = c.fg, bg = opts.transparent and c.none or c.bg },
    NormalNC       = { fg = c.fg, bg = opts.transparent and c.none or c.bg },
    Comment        = { fg = c.comment, style = opts.styles.comments },
    Constant       = { fg = c.orange },
    String         = { fg = c.green },
    Character      = { fg = c.green },
    Number         = { fg = c.orange },
    Boolean        = { fg = c.orange },
    Float          = { fg = c.orange },
    Identifier     = { fg = c.magenta, style = opts.styles.variables },
    Function       = { fg = c.blue, style = opts.styles.functions },
    Statement      = { fg = c.purple },
    Conditional    = { fg = c.purple },
    Repeat         = { fg = c.purple },
    Label          = { fg = c.purple },
    Operator       = { fg = c.cyan },
    Keyword        = { fg = c.purple, style = opts.styles.keywords },
    Exception      = { fg = c.purple },
    PreProc        = { fg = c.cyan },
    Include        = { fg = c.cyan },
    Define         = { fg = c.cyan },
    Macro          = { fg = c.cyan },
    PreCondit      = { fg = c.cyan },
    Type           = { fg = c.blue },
    StorageClass   = { fg = c.blue },
    Structure      = { fg = c.blue },
    Typedef        = { fg = c.blue },
    Special        = { fg = c.magenta },
    SpecialChar    = { fg = c.magenta },
    Tag            = { fg = c.magenta },
    Delimiter      = { fg = c.fg_dark },
    SpecialComment = { fg = c.comment, style = opts.styles.comments },
    Debug          = { fg = c.orange },
    Underlined     = { underline = true },
    Bold           = { bold = true },
    Italic         = { italic = true },
    Ignore         = { fg = c.comment },
    Error          = { fg = c.error },
    Todo           = { bg = c.yellow, fg = c.bg, bold = true },

    -- UI
    ColorColumn    = { bg = c.bg_dark },
    Cursor         = { fg = c.bg, bg = c.fg },
    CursorLine     = { bg = c.bg_highlight },
    CursorLineNr   = { fg = c.yellow, bold = true },
    LineNr         = { fg = c.fg_gutter },
    DiffAdd        = { bg = c.diff.add },
    DiffChange     = { bg = c.diff.change },
    DiffDelete     = { bg = c.diff.delete },
    DiffText       = { bg = c.diff.text },
    Directory      = { fg = c.blue },
    ErrorMsg       = { fg = c.error },
    Folded         = { fg = c.blue, bg = c.bg_dark },
    FoldColumn     = { fg = c.comment },
    IncSearch      = { bg = c.orange, fg = c.bg },
    Search         = { bg = c.yellow, fg = c.bg_dark },
    MatchParen     = { fg = c.orange, bold = true, underline = true },
    ModeMsg        = { fg = c.fg_dark, bold = true },
    MoreMsg        = { fg = c.blue },
    NonText        = { fg = c.fg_gutter },
    Pmenu          = { bg = c.bg_dark, fg = c.fg },
    PmenuSel       = { bg = c.bg_highlight },
    PmenuSbar      = { bg = c.bg_dark },
    PmenuThumb     = { bg = c.fg_gutter },
    SignColumn     = { bg = opts.transparent and c.none or c.bg, fg = c.fg_gutter },
    StatusLine     = { fg = c.fg_dark, bg = c.bg },
    StatusLineNC   = { fg = c.comment, bg = c.bg },
    TabLine        = { bg = c.bg_dark, fg = c.comment },
    TabLineFill    = { bg = c.bg_dark },
    TabLineSel     = { fg = c.fg, bg = c.blue },
    Title          = { fg = c.blue, bold = true },
    VertSplit      = { fg = c.border },
    Visual         = { bg = c.bg_visual, fg = c.bg_dark },
    WarningMsg     = { fg = c.warning },
    WildMenu       = { bg = c.bg_visual },
    WinSeparator   = { fg = c.border, bold = true },

    -- LSP
    LspReferenceText  = { bg = c.bg_highlight },
    LspReferenceRead  = { bg = c.bg_highlight },
    LspReferenceWrite = { bg = c.bg_highlight },
    DiagnosticError   = { fg = c.error },
    DiagnosticWarn    = { fg = c.warning },
    DiagnosticInfo    = { fg = c.info },
    DiagnosticHint    = { fg = c.hint },
    DiagnosticUnderlineError = { undercurl = true, sp = c.error },
    DiagnosticUnderlineWarn  = { undercurl = true, sp = c.warning },
    DiagnosticUnderlineInfo  = { undercurl = true, sp = c.info },
    DiagnosticUnderlineHint  = { undercurl = true, sp = c.hint },
  }
end

return M
