# Theme: floraverse_day
# By: solom4

theme[main_bg]="#f8f8f9"
theme[main_fg]="#666155"

# Title color for boxes
theme[title]="#666155"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#955311"

# Selected item in processes box
theme[selected_bg]="#f0f0f3"
theme[selected_fg]="#3a7d67"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#3a7d67"

# Cpu box outline color
theme[cpu_box]="#baabd1"

# Memory/disks box outline color
theme[mem_box]="#baabd1"

# Net up/down box outline color
theme[net_box]="#baabd1"

# Processes box outline color
theme[proc_box]="#baabd1"

# Box divider line and small boxes line color
theme[div_line]="#baabd1"

# Temperature graph colors
theme[temp_start]="#61702d"
theme[temp_mid]="#7f6020"
theme[temp_end]="#f32775"

# CPU graph colors
theme[cpu_start]="#61702d"
theme[cpu_mid]="#7f6020"
theme[cpu_end]="#f32775"

# Mem/Disk free meter
theme[free_start]="#61702d"
theme[free_mid]="#7f6020"
theme[free_end]="#f32775"

# Mem/Disk cached meter
theme[cached_start]="#3a7d67"
theme[cached_mid]="#7f6020"
theme[cached_end]="#f32775"

# Mem/Disk available meter
theme[available_start]="#368eb4"
theme[available_mid]="#7f6020"
theme[available_end]="#f32775"

# Mem/Disk used meter
theme[used_start]="#61702d"
theme[used_mid]="#7f6020"
theme[used_end]="#f32775"

# Download graph colors
theme[download_start]="#61702d"
theme[download_mid]="#7f6020"
theme[download_end]="#f32775"

# Upload graph colors
theme[upload_start]="#3a7d67"
theme[upload_mid]="#7f6020"
theme[upload_end]="#f32775"