# Theme: floraverse_midnight
# By: solom4

theme[main_bg]="#0A090F"
theme[main_fg]="#dbd1b9"

# Title color for boxes
theme[title]="#dbd1b9"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#cd751c"

# Selected item in processes box
theme[selected_bg]="#16151B"
theme[selected_fg]="#62caa8"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#62caa8"

# Cpu box outline color
theme[cpu_box]="#3f3059"

# Memory/disks box outline color
theme[mem_box]="#3f3059"

# Net up/down box outline color
theme[net_box]="#3f3059"

# Processes box outline color
theme[proc_box]="#3f3059"

# Box divider line and small boxes line color
theme[div_line]="#3f3059"

# Temperature graph colors
theme[temp_start]="#b4ce59"
theme[temp_mid]="#fac357"
theme[temp_end]="#d02063"

# CPU graph colors
theme[cpu_start]="#b4ce59"
theme[cpu_mid]="#fac357"
theme[cpu_end]="#d02063"

# Mem/Disk free meter
theme[free_start]="#b4ce59"
theme[free_mid]="#fac357"
theme[free_end]="#d02063"

# Mem/Disk cached meter
theme[cached_start]="#62caa8"
theme[cached_mid]="#fac357"
theme[cached_end]="#d02063"

# Mem/Disk available meter
theme[available_start]="#40a4cf"
theme[available_mid]="#fac357"
theme[available_end]="#d02063"

# Mem/Disk used meter
theme[used_start]="#b4ce59"
theme[used_mid]="#fac357"
theme[used_end]="#d02063"

# Download graph colors
theme[download_start]="#b4ce59"
theme[download_mid]="#fac357"
theme[download_end]="#d02063"

# Upload graph colors
theme[upload_start]="#62caa8"
theme[upload_mid]="#fac357"
theme[upload_end]="#d02063"